# As we wait for the long-running PR https://github.com/grantjenks/python-sortedcontainers/pull/107
# to be merged, here are our custom type annotations.
# These are technically stricter than what the library accepts.

from typing import (
    Callable,
    Any,
    Generic,
    TypeVar,
    Sequence,
    MutableSequence,
    Iterable,
    Protocol,
    overload,
)

class Comparable(Protocol):
    def __lt__(self, other: Comparable) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

T = TypeVar("T")

class SortedKeyList(MutableSequence[T]):
    def __init__(self, key: Callable[[T], Comparable]): ...
    def add(self, value: T) -> None: ...
    @overload
    def __getitem__(self, idx: int) -> T: ...
    @overload
    def __getitem__(self, idx: slice) -> MutableSequence[T]: ...
    @overload
    def __delitem__(self, idx: int) -> None: ...
    @overload
    def __delitem__(self, idx: slice) -> None: ...
    @overload
    def __setitem__(self, idx: int, val: T) -> None: ...
    @overload
    def __setitem__(self, idx: slice, val: Iterable[T]) -> None: ...
    def insert(self, idx: int, val: T) -> None: ...
    def __len__(self) -> int: ...
