from typing import Any

class Template:
    def __init__(self, filename: str): ...
    def get_def(self, name: str) -> DefTemplate: ...

class DefTemplate:
    def render(self, *args: Any, **kwargs: Any) -> str: ...
